import React, { useState } from 'react';

//const state = useState();



const AppHooksDemo = () =>{
    const [count,setCount] = useState(5);
    //count : current value
    //setCount : is a function to set updated value
    //useState(5) : setting initial value to 5

    function IncreNum(){
        setCount(count+1); //Updating the value on button click
        //Whatever value generated by 'setCount' methos,will get automatically maped to 'count'
    }
return (
    <>
    <h1>{count}</h1>
    <button onClick={IncreNum}>Click Me</button>
    </>
);

}

export default AppHooksDemo;
